version: '3.8'

services:
  app:
    image: clivern/lynx:0.11.9
    environment:
      VIRTUAL_HOST: example.com
      LETSENCRYPT_HOST: example.com
      LETSENCRYPT_EMAIL: lynx@example.com
      APP_NAME: Lynx
      APP_PORT: 4000
      APP_SECRET: koPmu7TJCwD8mttV9vgWUeU7iuu/zTPOR3sX4UalM9KkYEVGPfyi0PeTVzu1TT8C
      APP_HOST: localhost
      APP_HTTP_SCHEMA: http
      DB_USERNAME: root
      DB_PASSWORD: D1q9f0C2&PEW
      DB_HOSTNAME: db
      DB_DATABASE: lynx
      DB_PORT: 5432
      DB_SSL: null
      DB_CA_CERTFILE_PATH: null
      MIX_ENV: prod
    command: sh -c "/app/bin/migrate && /app/bin/server"
    restart: always
    depends_on:
      - db
      - nginx-proxy

  db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: lynx
      POSTGRES_USER: root
      POSTGRES_PASSWORD: D1q9f0C2&PEW
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data

  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
    restart: always

  docker-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-proxy-gen
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro # taken from https://raw.githubusercontent.com/nginx-proxy/nginx-proxy/main/nginx.tmpl 
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
      - docker-gen
    volumes_from:
      - nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs
      - ./acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy-gen
    restart: always

volumes:
  db:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  default:
    external:
      name: nginx-proxy
